services:
  homepage:
    image: example:latest
    container_name: example
    env_file: .env
    ports:
      - 3000:3000
    volumes:
      - /path/to/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: example
      tsdproxy.ephemeral: "false"
